### ISSUE TITLE
Merge commit necessary?

### ISSUE THREAD

**Issue by audiodude** [audiodude/odeon#29]
Does anybody know why, when I did a git pull origin master to my master branch, it caused https://github.com/audiodude/odeon/commit/9812b11c063f55dcff5b49c48cce9cbaf0929673 to be created?

cc: @rjulian @sashahart

**Comment by sashahart** [comment]
Don't know. I don't think anyone did push -f to master or anything...

**Comment by sashahart** [comment]
Nothing is happening on this
