### ISSUE TITLE
Clarification on "must"

### ISSUE THREAD

**Issue by sashahart** [audiodude/odeon#5]
There are many uses of the word "must" in the initial ruleset. For example, "Every eligible voter must participate in every vote on rule-changes."

If I try, I can get the sense from this that a proposed rule-change is never adopted unless every eligible voter responds with "+1" or "-1" on the PR. This is the interpretation that seems most orderly to me.

However, it seems at least equally natural to interpret this as mandating behavior on the part of the voters, in which case I am not sure what happens when the player does not do as the rules mandate: i.e., what is the implicit "or else" behind the "must"?

**Comment by audiodude** [comment]
My interpretation is that "must" just means the player can't get out of it. Like can't pass on voting.

On the other hand there are many ways in which the game could stall, primarily exactly like this: not everyone has voted and the rules require unanimity to pass a rule change and for everyone to vote.

So my interpretation is that the game just stalls at that point. The rules do not prescribe any penalty, therefore none is assumed to exist.

**Comment by sashahart** [comment]
Thanks. I understand this by analogy with abstract machines: if the game rules do not have a way to generate a next state, then there is no next state. You could say the machine hung or crashed (depending on whether a condition might later arise generating a valid next state according to the rules).
